[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }